name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy to S3
        run: |
          aws s3 sync ./dist s3://${DEPLOY_BUCKET} --delete
          aws cloudfront create-invalidation --distribution-id ${CLOUDFRONT_ID} --paths "/*"
